apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-microproject-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
