apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-microproject-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
